baseURL = 'http://noblehusein.github.io'
languageCode = 'en-us'
title = 'Husein Noble'
theme  = "hugo-theme-terminal-master"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"


[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "pink"

  fullWidthTheme = false
  centerTheme = true







